[package]
name = "parser"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
thiserror = "1.0.30"
scanner = { path = "../../crates/scanner" }

[dev-dependencies]
pretty_assertions = '1.1.0'

[features]
token = []
